
#Base de Datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
server.port=${SERVER_PORT}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.datasource.driver-class-name=org.postgresql.Driver


#swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui
springdoc.api-docs.path=/doc/v3/api-docs
springdoc.override-with-generic-response=false

#health checks
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always